### ISSUE TITLE
[generatedFilename]: 希望能自动创建目录

### ISSUE THREAD

**Issue by RSS1102** [varletjs/varlet-iconx#2]
- [ ] 希望当目录不存在的时候 尝试创建目录。
假设原目录为`./playground/assets`
想创建`./playground/assets/css/virtual.icons.css`
希望能自动尝试创建`css`目录。

- [ ] 当`generatedFilename`创建错误的时候希望能抛出错误。

**Comment by haoziqaq** [comment]
v0.2.6
